config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'home/about' => 'homes#about'
  get '/search', to: 'searches#search'
  devise_for :users

  resources :relationships, only: [:create, :destroy]

  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:show,:index,:edit,:update] do
    member do
     get :following, :followers
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user

	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id', dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :user

  attachment :profile_image, destroy: false
  validates :name, length: {maximum: 20, minimum: 2}, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @book_comment = @book.book_comments.new(book_comment_params)
    @book_comment.user_id = current_user.id
    @book_comment.save
    redirect_to book_path(@book)
  end

  def destroy
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    redirect_back(fallback_location: root_path)
  end

  private
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!
	before_action :ensure_correct_book, only: [:edit,:update]

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @book_comment = BookComment.new
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end



  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def ensure_correct_book
    @book = Book.find(params[:id])
    unless @book.user_id == current_user.id
      redirect_to books_path
    end
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    # 1pattern
    @favorite = @book.favorites.new(user_id: current_user.id)
    # 2pattern
    # @favorite = Favorite.new(book_id: @book.id, user_id: current_use.id)
    @favorite.save
    redirect_back(fallback_location: root_path)
  end
  def destroy
    @book = Book.find(params[:book_id])
    @favorite = @book.favorites.find_by(book_id: @book.id)
    @favorite.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  before_action :set_user

  def create
    @following = current_user.follow(@user)
    if @following.save
      flash[:success] = "フォローしました"
      redirect_back(fallback_location: root_path)
    else
      flash.now[:alert] = "フォローに失敗しました"
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    @following = current_user.unfollow(@user)
    if @following.destroy
      flash[:success] = "フォロー解除しました"
      redirect_back(fallback_location: root_path)
    else
      flash.now[:alert] = "フォロー解除に失敗しました"
      redirect_back(fallback_location: root_path)
    end
  end

  private
  def set_user
    @user = User.find(params[:follow_id])
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
    @model = params["search"] ["model"]
    @content = params["search"] ["content"]
    @method = params["search"] ["model"]
    @records = search_for(@model,@content,@method)
  end

  private
    def search_for(model,content,method)
      if model == 'user'
        if method == 'perfect'
          User.where(name: content)
        elsif method == 'forward'
          User.where('name LIKE ?', content+'%')
        elsif method == 'backward'
          User.where('name LIKE ?', '%'+content)
        else
          User.where('name LIKE ?', '%'+content+'%')
        end

      elsif model == 'book'
        if method == 'perfect'
          Book.where(title: content)
        elsif method == 'forward'
          Book.where('title LIKE ?', content+'%')
        elsif method == 'backward'
          Book.where('title LIKE ?', content+'%')
        else
          Book.where('title LIKE ?', '%'+content+'%')
        end
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit,:update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render 'edit'
    end
  end

  def following
    @user = User.find(params[:id])
  end

  def followers
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_with model:book, local:true do |f| %>
  <% if @book.errors.any? %>
		<div id="error_explanation">
			<h3><%= @book.errors.count %>error prohibited this obj from being saved:</h3>
			<ul>
				<% @book.errors.full_messages.each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
  <div class="field row">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'col-xs-12 book_title' %>
  </div>

  <div class="field row">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'col-xs-12 book_body' %>
  </div>

  <div class="actions row">
    <%= f.submit class: 'btn btn-primary col-xs-12' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user) do %>
          <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">

	<h1>Editing Book</h1>
	<% if @book.errors.any? %>
  <div id="error_explanation">
    <h2><%= @book.errors.count %>errors prohibited this book from being saved:</h2>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
        <% end %>
      </ul>
  </div>
  <% end %>
		<%= render "books/form", book: @book %>
		<%= link_to "Show", book_path(@book), class: "book_#{@book.id}" %>
		<%= link_to "Back", books_path, class: "back" %>

	</div>
	<div class="col-md-3"></div>

</div>

app/views/books/index.html.erb
<div class="container">
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>

		<h2>New book</h2>
		<%= render 'books/form', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Books index</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to user_path(book.user) do %>
							<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
					<td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>
					<td>
					  <% if book.favorited_by?(current_user) %>
				        <%= link_to book_favorites_path(book), method: :delete do %>
				          <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
				          <%= book.favorites.count %>
				      <% end %>
			          <% else %>
				        <%= link_to book_favorites_path(book), method: :post do %>
					      <span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span>
					      <%= book.favorites.count %>
				        <% end %>
			          <% end %>
					  コメント数:
					  <%= book.book_comments.count %>
					</td>
				</tr>
				<% end %>
			</tbody>
		</table>

		<!--books一覧 -->


	</div>
</div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
	<div class="col-xs-3">

<h2>User info</h2>
  <%= render 'users/profile', user: @book.user %>

<h2>New book</h2>
  <%= render 'books/form', book: @book_new %>

    </div>

	  <div class="col-xs-9">
	    <h2>Book detail</h2>

		<table class="table">
		  <tr>
		    <td>
		  	  <%= link_to user_path(@book.user) do %>
		  	    <%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
		  		<%= @book.user.name %>
		  	  <% end %>
		  	</td>
		  	<td><%= link_to @book.title, book_path(@book) %></td>
		  	<td><%= @book.body %></td>
            <td>
		  	  <% if @book.favorited_by?(current_user) %>
				  <%= link_to book_favorites_path(@book), method: :delete do %>
				    <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
				    <%= @book.favorites.count %>
				  <% end %>
			  <% else %>
				  <%= link_to book_favorites_path(@book), method: :post do %>
					 <span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span>
					 <%= @book.favorites.count %>
				  <% end %>
			  <% end %>
		  		  コメント数:
		  		  <%= @book.book_comments.count %>
		  	</td>
		  	<% if @book.user.id == current_user.id %>

		  	<td><%= link_to "Edit", edit_book_path(@book), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
		  	<td><%= link_to "Destroy", book_path(@book), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %></td>

		  	<% end %>
		  </tr>
			</table>


			<table class="table">
			<% @book.book_comments.each do |book_comment| %>
			  <%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><%= book_comment.user.name %>
			  <%= book_comment.comment %>
        <% if book_comment.user == current_user %>
          <%= link_to "destroy", book_book_comment_path(@book, book_comment), method: :delete, class: "btn btn-danger" %>
        <% end %>
      <% end %>
      </table>

			<%= form_for [@book,@book_comment] do |f| %>
			  <div class="row">
			  	<div class="col-sm-12">
			  		<%= f.text_area :comment, rows:'5', class: "form-control"%>
			  	</div>
			  </div>
			  <%= f.submit "送信", class: "btn btn-default" %>
			<% end %>
	</div>
</div>

app/views/homes/about.html.erb
<h1>Welcome to <span class='glyphicon glyphicon-book'></span><strong>Bookers</strong>!</h1>

app/views/homes/top.html.erb
<div class="row">
  <div class='top-message col-xs-offset-3 col-xs-6'>
    <h1>welcome to <span class='glyphicon glyphicon-book'></span><strong>Bookers</strong>  !!</h1>
    <p>In  <span class='glyphicon glyphicon-book'></span><strong>Bookers</strong>, </p>
    <p>you can share and exchange  your opinions , inpressions , and emotions</p>
    <p> about various books!</p>

    <div class="btn-wrapper">
      <div class="row">
        <p><%= link_to 'Log in', new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1" %></p>
      </div>
      <div class="row">
        <p><%= link_to 'Sign Up', new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1" %></p>
      </div>
    </div>

  </div>
</div>

app/views/searches/search.html.erb
<% if @model == 'user' %>
  <h3>Users search for '<%= @content %>'</h3>
  	<%= render 'users/index', users: @records %>

  <% else @model == 'books' %>
  <h3>Books search for '<%= @content %>'</h3>
    <%= render 'books/index', books: @records %>
<% end %>

app/views/users/_follow_button.html.erb
<% unless current_user == user %>
  <% if current_user.following?(user) %>
    <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'Unfollow', class: 'btn' %>
    <% end %>
  <% else %>
    <%= form_for(current_user.relationships.build) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'Follow', class: 'btn' %>
    <% end %>
  <% end %>
<% end %>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_profile.html.erb
<table class="table">
	<tr><%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %></tr>

	<tr>
		<th>name</th>
		<th><%= user.name %></th>
	</tr>

	<tr>
		<th>introduction</th>
		<th><%= user.introduction %></th>
	</tr>
	  <%= render 'users/stats' %>
</table>
<% if user.id == current_user.id %>
<div class="row">
	<%= link_to '', edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
</div>
<% end %>

app/views/users/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <tr>
    <th>following</th>
    <th>
      <%= link_to @user.followings.count, following_user_path(@user) %>
    </th>
  </tr>
  <tr>
    <th>followers</th>
    <th>
      <%= link_to @user.followers.count, followers_user_path(@user) %>
    </th>
  </tr>
</div>

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_with model:@user, local: true do |f| %>

	<!-- エラーメッセージ表示-->
	<% if @user.errors.any? %>
		<div id="error_explanation">
			<h3><%= @user.errors.count %>error prohibited this obj from being saved:</h3>
			<ul>
				<% @user.errors.full_messages.each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<!-- エラーメッセージ表示-->

	<div class="field">
		<%= f.label :title %>
		<%= f.text_field :name, class: "name" %>
	</div>

	<div class="field">
		<%= f.label :image %>
		<%= f.attachment_field :profile_image, class: "user_image" %>
	</div>

	<div class="field">
		<%= f.label :introduction %>
		<%= f.text_area :introduction, class: "introduction" %>
	</div>

	<div class="actions">
		<%= f.submit %>
	</div>

<% end %>

app/views/users/followers.html.erb
 <div class="container">
    <div class="row">
    	<div class="col-xs-10">
			<h2>Followers Users</h2>
			<table class="table">
				<thead>
					<tr>
						<th>image</th>
						<th>name</th>
						<th></th>
						<th></th>
						<th></th>
						<th></th>
					</tr>
				</thead>

				<tbody>
				  <% @user.followers.each do |user| %>
					<tr>
						<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
						<td><%= user.name %></td>
						<td>following：
						<%= user.followings.count %></td>
						<td>followers：
						<%= user.followers.count %></td>
						<td><%= link_to relationships_path(user), method: :post do %>
							unfollow
							<% end %></td>
						<td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/users/following.html.erb
<div class="container">
    <div class="row">
    	<div class="col-xs-10">
			<h2>Follow Users</h2>
			<table class="table">
				<thead>
					<tr>
						<th>image</th>
						<th>name</th>
						<th></th>
						<th></th>
						<th></th>
						<th></th>
					</tr>
				</thead>

				<tbody>
					<% @user.followings.each do |user| %>
					<tr>
						<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
						<td><%= user.name %></td>
						<td>following：
						<%= user.followings.count %></td>
						<td>followers：
						<%= user.followers.count %></td>
						<td><%= link_to relationship_path(user), method: :delete do %>
							unfollow
							<% end %>
						</td>
						<td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<%= flash[:notice] %>


<div class="container">
<div class="row">
<div class="col-xs-3">

<h2>User info</h2>
<%= render 'users/profile', user: current_user %>

<h2>New book</h2>
<%= render 'books/form', book: @book %>
</div>


<div class="col-xs-9">
<h2>Users</h2>
<!--users一覧 -->
<table class="table">
	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% @users.each do |user| %>
		<tr>
			<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
			<td><%= user.name %></td>
			<td>
				following:<%= user.followings.count %>
			</td>
			<td>
				followers:<%= user.followers.count %>
			</td>
			<td><%= render 'users/follow_button', user: user %></td>
			<td><%= link_to "Show", user_path(user), class: "user_#{user.id}" %></td>
		</tr>
		<% end %>
	</tbody>
</table>
</div>
</div>
</div>
<!--users一覧 -->

app/views/users/show.html.erb
<div class="container">
<div class="row">
	<div class="col-xs-3">
		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>
    <%= render 'users/follow_button', user: @user %>
		<h2>New book</h2>
		<%= render 'books/form', book: @book %>
	</div>

	<div class="col-xs-9">
		<h2>Books</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
					<tr>
						<td>
							<%= link_to user_path(book.user) do %>
								<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
							<% end %>
						</td>
						<td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
						<td><%= book.body %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
		<!--books一覧 -->
	</div>
</div>
</div>